### ISSUE TITLE
Possible error in the data types file

### ISSUE THREAD

**Issue by hnatiukr** [YK911/fson-81-jscore#1]
It's none of my business. I was just curious :)

But I noticed an error in the source code that can confuse someone. Perhaps this is not a mistake... then ignore the issue (and ban me 😄) 

[fson-81-jscore/js/dataTypes.js:8](https://github.com/YK911/fson-81-jscore/blob/main/js/dataTypes.js#L8)

```javascript
//TODO: типи даних в js

const str = `hello`;
const num = 234;
const symb = Symbol("hello");
const bool = true;
const bigInteger = BigInt(37827327382);
const arr = [];  // <--------------------------- here
const obj = {};
const und = undefined;
const nu = null;
```

You put an **array** as one of the data types, but an **array** is not a separate data type. 

**Array** is a built-in object in JavaScript that provides a set of methods for working with arrays.
 I understand that the array literal is a bit confusing, but you probably know what the result of this check will be:

```javascript
typeof [] === typeof {}
```

It's better to compare Array with similar built-in objects with a similar `typeof 'object'`, like a Number, String, Boolean, Date, Error, etc. 

There are several tricks to find out if an object is an array, like:
```javascript
Array.isArray([]) // true

[] instanceof Array // true

Object.prototype.toString.call([]) // "[object Array]" 
```

But that's a completely different story...

**Comment by YK911** [comment]
Hey 👋
Glad to see you) You are absolutely right, an array is a special case of an object. Here is an example to demonstrate and explain this  for students on line 16 and 17

```javascript
//TODO: типи даних в js

const str = `hello`;
const num = 234;
const symb = Symbol("hello");
const bool = true;
const bigInteger = BigInt(37827327382);
const arr = [];
const obj = {};
const und = undefined;
const nu = null;

// console.log(typeof bigInteger)
// console.log(typeof str)
// console.log(typeof num)
// console.log(typeof arr) // 👈
// console.log(typeof obj) // 👈
```
